name: Build Theme ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Usunięto krok "Read version from style.css"

      - name: Prepare build directory
        run: |
          mkdir -p build/dominium
          rsync -av . build/dominium \
            --exclude=.git/ \
            --exclude=.github/ \
            --exclude=README.md \
            --exclude=*.zip \

      - name: Create ZIP file
        run: |
          cd build
          # Stała nazwa pliku: dominium.zip
          zip -r "dominium.zip" dominium

      - name: Upload ZIP to Release
        run: |
          # Przesłanie pliku dominium.zip do Release
          gh release upload ${{ github.event.release.tag_name }} "build/dominium.zip" \
            --repo $GITHUB_REPOSITORY --name dominium.zip --clobber
        env:
          # Użycie domyślnego tokena
          GH_TOKEN: ${{ github.token }}