name: Build Theme ZIP

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ZIP package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build directory
        run: |
          mkdir build
          rsync -av . build/dominium --exclude=.git/ --exclude=.github/ --exclude=.gitignore --exclude=README.md --exclude=LICENSE --exclude=CHANGELOG.md --exclude=*.zip --exclude=node_modules/

      - name: Create ZIP file
        run: |
          cd build
          zip -r dominium.zip dominium

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/dominium.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
